name: Calcular hashes MD5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  calculate_md5:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Executar script
      run: |
        bash files.sh
        echo "Lista de arquivos:" > lista_arquivos.txt
        cat filelist.txt >> lista_arquivos.txt
        bash group.sh

    - name: Salvar artefatos
      uses: actions/upload-artifact@v2
      with:
        name: arquivo-artefato
        path: |
          FilesList.md
          lista_arquivos.txt
          HashList.txt
